### ISSUE TITLE
App crashs when keyboard appear

### ISSUE THREAD

**Issue by AownMohammad** [bassaer/ChatMessageView#13]
Here is error:
` java.lang.NullPointerException: Attempt to invoke interface method 'void com.github.bassaer.chatmessageview.views.MessageView$OnKeyboardAppearListener.onKeyboardAppeared(boolean)' on a null object reference
                      at com.github.bassaer.chatmessageview.views.MessageView.onSizeChanged(MessageView.java:139)`

**Comment by felHR85** [comment]
It also happened to me. Do you have any clue?

**Comment by AownMohammad** [comment]
No I dont have any clue, I rather used my own CardView with Adapter for ChatView

**Comment by bassaer** [comment]
This issue was fixed by @taru-m 
Please update v1.3.2
Thanks!

**Comment by felHR85** [comment]
Thanks! @bassaer!! I will give it a try!
