### ISSUE TITLE
The keyboard is automatically hidden

### ISSUE THREAD

**Issue by amirch123** [bassaer/ChatMessageView#14]
hello
After post, the keyboard is automatically hidden.
How do I prevent this?

thanks

**Comment by bassaer** [comment]
Hi @amirch123,
Currently not supported.
So you need to modify this lib.

https://github.com/bassaer/ChatMessageView/blob/master/chatmessageview/src/main/java/com/github/bassaer/chatmessageview/views/ChatView.java#L130

just remove this line.

But the keyboard options you want will be included next update within few days.
Thanks.

**Comment by bassaer** [comment]
Added your request in version 1.3.3

```
mChatView.setAutoHidingKeyboard(false);
```
Give it a try!
Thanks.

**Comment by amirch123** [comment]
Thank you for your support
