### ISSUE TITLE
ChatView Always scrolling from Top to Bottom 

### ISSUE THREAD

**Issue by pawarn** [bassaer/ChatMessageView#142]
I am using ChatView in my project. When I am setting List of message history to ChatView first-time chatView scrolling form first message to last msg. For single message it is working good.

So can we have such a method where I can set List of messages to ChatView And setScroll bottom always? So  It will not scroll from first to last.

I tried  mChatView.scrollToEnd(); and mChatView.setAutoScroll(false); But it didnt work for me.

My Code Example.

     for (UserMessage userMessage : userMessageList) {
                Random random = new Random();

                UserMsg userMsg = new UserMsg(""+random.nextInt(), userMessage.getUserName(), myIcon);

     //   Calendar msgTime = Calendar.getInstance();
       //                msgTime.setTimeInMillis(Long.valueOf(userMessage.getTime()));
                    final Message msg = new Message.Builder()
                        .setUser(userMsg)
                        //.setSendTime(msgTime)
                        .setText(userMessage.getMessage())
                        .hideIcon(true)
                        .setUsernameVisibility(true)
                        .build();

            if (userMessage.getFrom().equalsIgnoreCase(farmerId)) {
                mChatView.send(msg);
                msg.setRight(true);
            } else {
                msg.setRight(false);
                mChatView.receive(msg);
                
            }
     }

**Comment by bassaer** [comment]
@pawarn 
try this
```
// mChatView.getMessageView().setSelection(<the number of messages>) 
mChatView.getMessageView().setSelection(mChatView.getMessageView().getMessageList().size());
```

this is a sample project. please check this out if you need.
https://github.com/bassaer/ChatMessageViewSample/blob/master/app/src/main/java/com/github/bassaer/chatmessageviewsample/MainActivity.java

**Comment by pawarn** [comment]
Thanks,
@bassaer  This work for me.

And thanks for the great library.
