### ISSUE TITLE
Add Camera button at option menu

### ISSUE THREAD

**Issue by AndreasGeorgopoulos** [bassaer/ChatMessageView#143]
I would like to ask you if there is a way to add a camera button at the option menu and how can I access the onClick event to generate a new procedure when the user clicks on it.

**Comment by bassaer** [comment]
yes, there is.

please check below
https://github.com/bassaer/ChatMessageView/blob/master/example/src/main/java/com/github/bassaer/example/MessengerActivity.java#L188-L193

https://github.com/bassaer/ChatMessageView/blob/master/example/src/main/java/com/github/bassaer/example/MessengerActivity.java#L94-L95

**Comment by AndreasGeorgopoulos** [comment]
Thank you very much for your response. Following up your reply, is it possible to catch a user's click on the mic button (google keyboard) at your implementation to trigger an activity?

**Comment by bassaer** [comment]
No, it isn't.
you can use the mic button on keyboard to input message in EditText

<img src="https://user-images.githubusercontent.com/14991643/40122015-d70d8572-595d-11e8-9829-18789bb0cc00.png" height=500>
