### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by modularthoughts** [bassaer/ChatMessageView#146]
Is there a way to make the text inside the bubbles selectable for copying?

**Comment by bassaer** [comment]
@modularthoughts 
Thanks for your comment.
please update 1.11.0
and add this code in your xml
https://github.com/bassaer/ChatMessageView/blob/master/example/src/main/res/layout/activity_messenger.xml#L17

**Comment by modularthoughts** [comment]
Thank you very much!
