### ISSUE TITLE
Is there a way that I could highlight a message?

### ISSUE THREAD

**Issue by amirch123** [bassaer/ChatMessageView#15]
Hello
Is there a way that I could highlight a message with programing?
For example, I highlight a message (3)
thanks

**Comment by bassaer** [comment]
you mean you want change just one bubble color, not all of them?

**Comment by amirch123** [comment]
Yes
For example, when clicking on a message number one, message number four is highlighted

**Comment by bassaer** [comment]
Currently not supported.
