### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by slagusev** [bassaer/ChatMessageView#158]
Application not run
Error:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{myapp.home.com.myapp/myapp.home.com.myapp.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.github.bassaer.chatmessageview.views.ChatView`

**Comment by bassaer** [comment]
@slagusev 
Thanks for letting me know
please use v1.11.0 for now.

**Comment by slagusev** [comment]
Thanks! It's version work
