### ISSUE TITLE
i want clear data how do this

### ISSUE THREAD

**Issue by kickstartinteractiveandroidteam** [bassaer/ChatMessageView#17]

**Comment by kickstartinteractiveandroidteam** [comment]
after chat in my case need to clear all chat  how make this

**Comment by bassaer** [comment]
This function will be included next version

**Comment by mohammad-rababah** [comment]
you can use this
                        ((MessageView)(chatView.findViewById(R.id.message_view))).init(new ArrayList<Message>());

**Comment by bassaer** [comment]
Thanks!
