### ISSUE TITLE
Change Text Size ? 

### ISSUE THREAD

**Issue by ashok1994** [bassaer/ChatMessageView#19]
Please help decreasing the font size

**Comment by xbroak** [comment]
I would also like to see this please

**Comment by nimaaaaw** [comment]
yea that would be big help

**Comment by nimaaaaw** [comment]
@ashok1994 @xbroak @bassaer 
guys I found out that u can override these values in your project's dimen file
and it changed the font sizes!
font_normal is for the message text 
font_small for username text

`<dimen name="font_normal">14sp</dimen>`
`<dimen name="font_small">12sp</dimen>`


Hope it Helps.

**Comment by bassaer** [comment]
This function will be included next version.
