### ISSUE TITLE
Chat bubble being distorted by Activity State

### ISSUE THREAD

**Issue by froesmatheus** [bassaer/ChatMessageView#2]
Hi, I was doing some tests with the library and I realized that when the app goes to background and come back, the chat bubbles are not rounded anymore. 

Example:
![screenshot_20170106-211737](https://cloud.githubusercontent.com/assets/8764566/21737253/527a27e6-d45e-11e6-8139-1809843a7c55.png)

Hope it helps.

**Comment by bassaer** [comment]
Thanks @froesmatheus !
