### ISSUE TITLE
Possibility to dynamically update status?

### ISSUE THREAD

**Issue by elmalote** [bassaer/ChatMessageView#20]
Hi
Thanks for a great library.

I have an enhancement request.

There is no possibility to update the message status dynamically as the chat view doesn't let us retrieve the single Message item.

Could you add this?

**Comment by bassaer** [comment]
Thanks for your request.
I'll consider that!

**Comment by dengue8830** [comment]
there is no way to update the status icon? on send, i want to display the message with the delivering status icon, and if there was an error update the status icon of the message item to an error icon, or if the message have been successfully delivered change the icon to a check icon. How can i achieve this behavior?

**Comment by wprenison** [comment]
@bassaer Thanks for the great lib, I agree with @dengue8830  this would be valuable feature
@dengue8830 I've managed to achieve this with a bit of a hack accessing the view directly:

`View msgView = chatView.getMessageView().getChildAt(chatView.getMessageView().getChildCount()-1);
                                ImageView imgvStatusIcon = msgView.findViewById(R.id.status_icon_image_view);
                                imgvStatusIcon.setImageDrawable(utilMsgStatus.getStatusIcon(UtilMsgStatus.STATUS_DELIVERED, true));`

Keep in mind this only accesses the last message in the message view so if you have add another you will have to write some code to handle it. Also if the lib is updated and the R.id.status_icon_image_view is changed for some reason the view won't be found with this code.
