### ISSUE TITLE
Set date for messages

### ISSUE THREAD

**Issue by danielbeicht** [bassaer/ChatMessageView#22]
Hi,

is it possible to set the date/time for every message? I don't want to see the date when the message was created in Android but the date when the message was actually send and stored in the database.

Does something like following (setTime) exists?
Message message = new Message.Builder()
                        .setUser(me)
                        .setRightMessage(true)
                        .setMessageText(mChatView.getInputText())
                        .hideIcon(true)
.setTime(1498559503 )
                        .build();

**Comment by bassaer** [comment]
Hi,
Yes it is.

```
Calendar calendar = Calendar.getInstance();
calendar.setTimeInMillis(1498527063);

Message message = new Message.Builder()
.setCreatedAt(calendar)
.build();
```
