### ISSUE TITLE
Received messages not visible in chat

### ISSUE THREAD

**Issue by lemonov** [bassaer/ChatMessageView#26]
After start of activity the scrolling of chat outgoing messages work. The received messages are not visible yet when I manually scroll the view they appear from the bottom of view (that expands itself with each new message). It seems that MessageView is not refreshed or scrolled after each new message. Can I trigger it somehow from your API?

**Comment by bassaer** [comment]
Did you use MessageView or ChatView?

**Comment by lemonov** [comment]
ChatView

**Comment by bassaer** [comment]
try this
```
mChatView.setAutoScroll(true);
```

**Comment by lemonov** [comment]
I saw this is set by default. The issue seems to be that notification for ListView adapter is not received.

**Comment by iddqdidkfa** [comment]
@lemonov can you reproduce it in example project?

**Comment by lemonov** [comment]
After long haul i managed to fix my issue. The problem was that notifyDataSetChanged from ArrayAdapter will not trigger the change if it is called from UIThread. Fix for this was simple: 
`            runOnUiThread(() -> chat_view.receive(receivedMessage));
`
to push the receiving from (in my case) network handling thread logic to UI Thread.
