### ISSUE TITLE
How to customize edittext? (Delete underline.)

### ISSUE THREAD

**Issue by lyw0149** [bassaer/ChatMessageView#27]
How to customize edittext? (Delete underline.)

**Comment by bassaer** [comment]
Unfortunately cannot customize EditText of ChatView.
So you need to implement customized EditText with MessageView to achieve what you want to do.
Thanks.

**Comment by lyw0149** [comment]
FYI

For delete just underline, 

(kotlin)
val messageEditText = this.findViewById(R.id.message_edit_text) as EditText
messageEditText.setBackgroundColor(Color.TRANSPARENT)

this code will delete underline.
