### ISSUE TITLE
Reduce spacing between views in chatview

### ISSUE THREAD

**Issue by chitrey** [bassaer/ChatMessageView#3]
How can I reduce the margin between the text views in chat view???

**Comment by bassaer** [comment]
You mean this?

<img src="https://cloud.githubusercontent.com/assets/14991643/21846124/ee1f0eb8-d838-11e6-94b5-5ef71f597eaf.png" height="540dp">

**Comment by chitrey** [comment]
yes exactly :)

**Comment by chitrey** [comment]
also can we hide the text view which shows the username?? I'd like the image and the message aligned horizontally. If it was possible to hide the username view i think i could  achieve this. Thank for your help

**Comment by bassaer** [comment]
Currently not supported, but should be.
So these settings will be included next update.
Thanks!

**Comment by chitrey** [comment]
Looking forward to it!! (Y)

**Comment by bassaer** [comment]
Added these settings to version 1.2.2.
If you want to
- add margin to top or bottom of the bubble
ChatView#setMessageMarginTop(int);
ChatView#setMessageMarginBottom(int); 

- hide username
Message#setUsernameVisibility(boolean)

- hide user icon
Message#hideIcon(boolean)

```
ChatView chatView = (ChatView)findViewById(R.id.chat_view);
chatView.setMessageMarginTop(5);
chatView.setMessageMarginBottom(5);

Message message = new Message.Builder()
                        .setUser(me)
                        .setRightMessage(true)
                        .setMessageText(mChatView.getInputText())
                        .hideIcon(true)
                        .build();
```

Hope this helps!

**Comment by chitrey** [comment]
Thank you so much. It did help :) I hope you can make image sending possible in upcoming updates. Cheers

**Comment by bassaer** [comment]
I plan on adding image sending to upcoming update.
Thanks!
