### ISSUE TITLE
Async load images causes message to appear at bottom

### ISSUE THREAD

**Issue by DaveMurchison83** [bassaer/ChatMessageView#33]
I'm retrieving a list of messages from my server with some being an image instead of text. I'm loading the images as a bitmap using Picasso/Glide, however due to this being an async process, this is done in the background, which means other messages are getting added whilst the image is being loaded into a bitmap.

The result is that messages are not ordered correctly, with messages that have an image showing further down the message view instead of in date order, as expected.

Is there a way to correct this?

**Comment by DaveMurchison83** [comment]
Is this going to be looked into? Am I the only one having this issue?

**Comment by bassaer** [comment]
@DaveMurchison83 
sorry for late reply.
this issue was fixed!
please update v1.5.5
