### ISSUE TITLE
Chat view not visible

### ISSUE THREAD

**Issue by Swat24** [bassaer/ChatMessageView#40]
Hi,
i try to use this library with your example code, but on device visible only text input and send message button.
`android:layout_height="match_parent"`
![screenshot_2](https://user-images.githubusercontent.com/17088705/31337578-a1ffc4a4-ad04-11e7-92f5-7b4b2011e273.jpg)

![screenshot_1](https://user-images.githubusercontent.com/17088705/31337548-7dde843e-ad04-11e7-9bb9-a6218b7f0a54.jpg)

If i set height manual:
`android:layout_height="300dp"`
chat view is visible.
![screenshot_3](https://user-images.githubusercontent.com/17088705/31337645-f166300a-ad04-11e7-95c0-f600d111f838.jpg)
![screenshot_4](https://user-images.githubusercontent.com/17088705/31337649-f6bc4a62-ad04-11e7-9320-64b5f8f0d3b1.jpg)

What wrong? Why "match_parent" not working?

**Comment by bassaer** [comment]
Hi,
[this](https://github.com/bassaer/ChatMessageViewSample) is a minimum sample code for ChatMessageView(version 1.3.5).

and its screen.

<img src="https://user-images.githubusercontent.com/14991643/31341129-7dcbc8c8-ad43-11e7-90ae-54ef38594d5f.png" height="500"/>

activity_main.xml

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.github.bassaer.chatmessageview.views.ChatView
        android:id="@+id/chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</LinearLayout>
```
it works. so I don't know why.

But there is a fab in your screen, you use its layout in your other layout file, don't you?
if so, please check your parent layout.

Thanks.

**Comment by Swat24** [comment]
Main screen have only this:

>     <android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     xmlns:tools="http://schemas.android.com/tools"
>     android:id="@+id/drawer_layout"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:fitsSystemWindows="true"
>     tools:openDrawer="start">
> 
>     <include
>         layout="@layout/app_bar_main"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent" />
> 
>     <android.support.design.widget.NavigationView
>         android:id="@+id/nav_view"
>         android:layout_width="wrap_content"
>         android:layout_height="match_parent"
>         android:layout_gravity="start"
>         android:fitsSystemWindows="true"
>         app:headerLayout="@layout/nav_header_main" />
> 
>     </android.support.v4.widget.DrawerLayout>

All other in fragment:

> 		<LinearLayout
> 		xmlns:android="http://schemas.android.com/apk/res/android"
> 		android:layout_width="match_parent"
> 		android:layout_height="match_parent"
> 		android:orientation="vertical">
> 
> 	 		<com.github.bassaer.chatmessageview.views.ChatView
> 			android:id="@+id/chat_view"
> 			android:layout_width="match_parent"
> 			android:layout_height="match_parent"/>
> 
>  		</LinearLayout>

Fab is hidden now
![screenshot_6](https://user-images.githubusercontent.com/17088705/31342843-8b91f946-ad16-11e7-98b5-4faf050a3e99.jpg)

**Comment by bassaer** [comment]
please remove ScrollView if possible.

```

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:id="@+id/content_main"
android:layout_width="match_parent"
android:layout_height="match_parent"
app:layout_behavior="@string/appbar_scrolling_view_behavior"
tools:context="ua.com.bioprom.biouniversal.ui.activities.MainActivity"
tools:showIn="@layout/app_bar_main">

    <FrameLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/fragment" />

...

```

**Comment by bassaer** [comment]
also check [Navigation Drawer + ChatMessageView sample layouts](https://github.com/bassaer/ChatMessageViewSample/tree/master/app/src/main/res/layout) (***_second.xml)

Thanks.
