### ISSUE TITLE
Create Deliver icon on message. Showing fail icon if the message is not delivered

### ISSUE THREAD

**Issue by faizandedia** [bassaer/ChatMessageView#5]
Is there anyway to show custom view on message? I want to show delivery status on each message? how to do it?

**Comment by bassaer** [comment]
You mean like this?

<img src="https://cloud.githubusercontent.com/assets/14991643/23017836/28bb1d7a-f47f-11e6-9014-2efb1de2355e.png" height="540">

**Comment by faizandedia** [comment]
Yeah, but I want to show it to right.

**Comment by bassaer** [comment]
Unfortunately the delivery status  is supported only above the timestamp. 
So you will have to modify the library to achieve what you want to do.
