### ISSUE TITLE
Right/Left bubble color cannot be changed in Android 4.x / 5.x

### ISSUE THREAD

**Issue by rockwillj** [bassaer/ChatMessageView#6]
Hi, thank you for providing a great plugin.

I wrote the following test code.

```kotlin
chatView.setRightBubbleColor(Color.YELLOW)
chatView.setLeftBubbleColor(Color.YELLOW)
```

### Android 6.0.1 (Nexus 5X)

It works in Android 6.x.

<img src="https://cloud.githubusercontent.com/assets/14067182/22971580/7f32c8ea-f3b9-11e6-9921-7783a824a1cd.png" title="Android 6.0.1 (Nexus 5X)" width="300px" />

### Android 5.0.1 (Nexus 5)

But It does not work in Android 5.x. And same in Android 4.x.

<img src="https://cloud.githubusercontent.com/assets/14067182/22971572/7acaa570-f3b9-11e6-9d3c-066c8971b446.png" title="Android 5.0.1 (Nexus 5)" width="300px" />

Is this a bug? Or am I wrong?

**Comment by bassaer** [comment]
Hi @rockwillj,
Thank you for letting me know. 
I examined some bugs you found.
These bugs will be fixed next update.
Thanks!

**Comment by rockwillj** [comment]
Hi @bassaer,

Wow it's a good news. I'm looking forward to next update. Thank you!
