### ISSUE TITLE
error civ_border_width has already been defined

### ISSUE THREAD

**Issue by jyenes** [bassaer/ChatMessageView#7]
First of all thanks for your work, I hope you can help me.
I'm getting an issue once I added the dependency in the project, any way to solve the issue?

Error:(387) Attribute "**civ_border_width**" has already been defined

**Comment by bassaer** [comment]
Hi @jyenes,
I have never seen this issue before but I think it is related to support library.
Please check out the below links.

http://stackoverflow.com/questions/26432123/lollipop-appcompat-v7-21-attribute-theme-has-already-been-defined

http://stackoverflow.com/questions/32441420/attribute-barlength-has-already-been-defined

Hope that helps.
