### ISSUE TITLE
Multiline text

### ISSUE THREAD

**Issue by DaveMurchison83** [bassaer/ChatMessageView#74]
Can you alter the layout so that editext ("message_edit_text") can be set as multiline? Writing more than a sentence means the text scrolls from left to right and hides part of it out of view.

I tried altering this myself programatically but it won't work correctly as the LinearLayout it's wrapped in can't have it's height changed to WRAP_CONTENT. It needs given an ID. Or perhaps it should be given another dimension string other than @dimen/icon_normal that we can alter.

**Comment by bassaer** [comment]
@DaveMurchison83 
please update 1.6.0

![example](https://github.com/bassaer/ChatMessageView/blob/master/example/src/main/java/com/github/bassaer/example/MessengerActivity.java#L100)
```
mChatView.setMaxInputLine(5);
```


<img src="https://user-images.githubusercontent.com/14991643/33134966-7a38fc6c-cfe4-11e7-88fd-c41cd42b597d.png" height="500"/>

**Comment by DaveMurchison83** [comment]
Excellent, worked perfectly.
