### ISSUE TITLE
example MessengerActivity  leaks memory 

### ISSUE THREAD

**Issue by dsfjd** [bassaer/ChatMessageView#82]
Hey i was wondering why the memory was increasing while re-launching the MessengerActivity in the example directory so i tryed to find something in the java heap while re-launching but i didnt had enough experience to find something. Then i found [LeakCanary](https://github.com/square/leakcanary) a Library that helps you to find memory leaks i used it to find leaks in your MessengerActivity and get this result but i do not have that much experience to interpret it pls help me :)
ps: I have the same leak in my application 
![screenshot](https://user-images.githubusercontent.com/31368211/33453750-10a55190-d617-11e7-991a-6c89307eab8e.png)

**Comment by bassaer** [comment]
@dsfjd 
Thanks for the information!
Let me check
