### ISSUE TITLE
Is there any way to get current messages are displayed?

### ISSUE THREAD

**Issue by trinhvanminh2009** [bassaer/ChatMessageView#84]
I'm using the server to get data. I want to compare old messages with the new message to add into list Messages. But No way to clear current list messages. So I want to find another way to get current messages are displayed?

**Comment by bassaer** [comment]
you don't have to consider that.
All messages are sorted by sent time automatically when you use ```MessageView#setMessage(Message)``` or ```ChatView#send(Message)```.
