### ISSUE TITLE
Clear list of messages

### ISSUE THREAD

**Issue by takamoto-masahiro** [bassaer/ChatMessageView#86]
Hello.
Thanks for a great library.

Until version 1.4.1, I cleared it by calling MessageView 's init method.

It seems that it will not be cleared in later versions, so I'm very happy to have a method to clear the list of messages.

**Comment by bassaer** [comment]
@takamoto-masahiro 
Thanks for the information!
Let me check.

**Comment by matrenitski** [comment]
Yup, same problem. When switching between users, calling                  
`chatView.getMessageView().init();`
does not delete messages.

I think we could 
linearLayout.removeView(chatView);`
`and then recreate the ChatView programmatically, but may be there is other way?

**Comment by bassaer** [comment]
@takamoto-masahiro @matrenitski 
please update 1.7.0

also please check this out.
https://github.com/bassaer/ChatMessageView/wiki/Remove-Message-form-MessageView-ChatView

Thanks.
