### ISSUE TITLE
How to clear ChatView?

### ISSUE THREAD

**Issue by mr746866** [bassaer/ChatMessageView#9]
I want to clear/remove all messages from a ChatView.

**Comment by mr746866** [comment]
Also there should be an API to get the MessageView from ChatView.

**Comment by taru-m** [comment]
@bassaer こちらのissueですが、ChatViewからMessageViewを操作したい場合、また、トリッキーな処理でMessageAdapterを利用したい事があります。現状、reflectionで対応していますが可能であればgetterを作成していただけると助かります。
よろしくお願いいたしますm(_ _)m

**Comment by bassaer** [comment]
@mr746866 
Sorry for late reply.
Your request will be include in next update.

@taru-m 
コメントありがとうございます！
こちらの処理も次のアップデートで実装致します。
また、プルリクの方もありがとうございます。
確認後マージ致します。

**Comment by mohammad-rababah** [comment]
you can use this
                        ((MessageView)(chatView.findViewById(R.id.message_view))).init(new ArrayList<Message>());

**Comment by bassaer** [comment]
@mohammad-rababah Thanks!

**Comment by trinhvanminh2009** [comment]
@mohammad-rababah init(new ArrayList()); is private function. I can't access. How can you access that?
